const fs = require('node:fs/promises');
const path = require('node:path');
const sharp = require('sharp');

const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png']);
const IGNORED_DIRECTORY_NAMES = new Set(['_mediapolotx_backup', '_mediapolotx_no_ai']);
const AI_SIGNATURES = [
  'c2pa',
  'content credentials',
  'adobe:urn:uuid',
  'adobe_cai',
  'manifeststore',
  'ai-generated',
  'generated by ai'
];

async function scanFolder(folderPath, options = {}) {
  const includeJpg = options.includeJpg !== false;
  const includePng = options.includePng !== false;
  const files = [];

  await walk(folderPath, async (filePath, stats) => {
    const ext = path.extname(filePath).toLowerCase();
    if (!IMAGE_EXTENSIONS.has(ext)) return;
    if (path.basename(filePath).includes('.mediapolotx-tmp')) return;
    if ((ext === '.jpg' || ext === '.jpeg') && !includeJpg) return;
    if (ext === '.png' && !includePng) return;

    const detection = await detectAiMarkers(filePath);
    files.push({
      id: filePath,
      absolutePath: filePath,
      relativePath: normalizeRelativePath(path.relative(folderPath, filePath)),
      extension: ext === '.jpeg' ? 'jpg' : ext.slice(1),
      sizeBytes: stats.size,
      hasAiMarkers: detection.hasAiMarkers,
      markers: detection.markers
    });
  });

  return files.sort((a, b) => a.relativePath.localeCompare(b.relativePath));
}

async function processFolder(folderPath, options = {}, onProgress = null) {
  const outputDir = options.outputDir || path.join(folderPath, '_mediapolotx_no_ai');
  const replaceOriginal = options.replaceOriginal === true;
  const backupOriginal = options.backupOriginal !== false;
  const backupDir = options.backupDir || getDefaultBackupDir(folderPath);
  const files = options.files?.length ? options.files : await scanFolder(folderPath, options);
  const selectedPaths = new Set(options.selectedPaths || files.map((file) => file.absolutePath));
  const selectedFiles = files.filter((file) => selectedPaths.has(file.absolutePath));
  const results = [];

  onProgress?.({
    phase: 'start',
    total: selectedFiles.length,
    completed: 0,
    percent: 0
  });

  for (const file of selectedFiles) {
    const currentIndex = results.length + 1;
    onProgress?.({
      phase: 'processing',
      total: selectedFiles.length,
      completed: results.length,
      percent: selectedFiles.length ? Math.round((results.length / selectedFiles.length) * 100) : 0,
      currentFile: file.relativePath
    });

    const normalizedRelativePath = file.relativePath.replace(/\.(jpeg|jpg|png)$/i, (match) => (
      match.toLowerCase() === '.jpeg' ? '.jpg' : match.toLowerCase()
    ));
    const outputPath = replaceOriginal
      ? file.absolutePath
      : path.join(outputDir, normalizedRelativePath);
    const tempOutputPath = replaceOriginal
      ? createTempPath(file.absolutePath)
      : outputPath;
    const detection = await detectAiMarkers(file.absolutePath);
    await sanitizeImage(file.absolutePath, tempOutputPath, options);

    if (replaceOriginal) {
      if (backupOriginal) {
        const backupPath = path.join(backupDir, file.relativePath);
        await fs.mkdir(path.dirname(backupPath), { recursive: true });
        await fs.copyFile(file.absolutePath, backupPath);
      }
      await fs.rename(tempOutputPath, file.absolutePath);
    }

    results.push({
      inputPath: file.absolutePath,
      outputPath,
      replacedOriginal: replaceOriginal,
      relativePath: file.relativePath,
      removedAiMarkers: detection.hasAiMarkers,
      markers: detection.markers
    });

    onProgress?.({
      phase: 'processing',
      total: selectedFiles.length,
      completed: currentIndex,
      percent: selectedFiles.length ? Math.round((currentIndex / selectedFiles.length) * 100) : 100,
      currentFile: file.relativePath
    });
  }

  onProgress?.({
    phase: 'completed',
    total: selectedFiles.length,
    completed: selectedFiles.length,
    percent: 100
  });

  return {
    count: results.length,
    outputDir: replaceOriginal ? folderPath : outputDir,
    backupDir: replaceOriginal && backupOriginal ? backupDir : null,
    files: results
  };
}

async function detectAiMarkers(filePath) {
  const buffer = await fs.readFile(filePath);
  const lower = buffer.toString('latin1').toLowerCase();
  const markers = AI_SIGNATURES.filter((signature) => lower.includes(signature));
  return {
    hasAiMarkers: markers.length > 0,
    markers
  };
}

async function sanitizeImage(inputPath, outputPath, options = {}) {
  await fs.mkdir(path.dirname(outputPath), { recursive: true });

  const ext = path.extname(outputPath).toLowerCase();
  let pipeline = sharp(inputPath, { limitInputPixels: false }).rotate();
  const metadata = await sharp(inputPath).metadata();

  if (options.watermark?.enabled) {
    pipeline = pipeline.composite([{
      input: createWatermarkSvg(metadata.width || 1600, metadata.height || 1200, options.watermark),
      gravity: 'southeast'
    }]);
  }

  if (ext === '.png') {
    await pipeline.png({ compressionLevel: 6, adaptiveFiltering: true }).toFile(outputPath);
  } else {
    await pipeline.jpeg({ quality: Number(options.jpegQuality || 95), mozjpeg: true }).toFile(outputPath);
  }

  return { outputPath };
}

function createWatermarkSvg(width, height, watermark) {
  const text = escapeXml(watermark.text || 'qtddp');
  const fontSize = Number(watermark.fontSize || 32);
  const opacity = Number(watermark.opacity ?? 0.45);
  const color = watermark.color || 'rgb(80,80,80)';
  const padding = Math.max(24, Math.round(Math.min(width, height) * 0.035));

  return Buffer.from(`
    <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      <text x="${width - padding}" y="${height - padding}"
        text-anchor="end"
        font-family="Arial, Microsoft YaHei, sans-serif"
        font-size="${fontSize}"
        fill="${escapeXml(color)}"
        fill-opacity="${opacity}">${text}</text>
    </svg>
  `);
}

async function walk(root, onFile) {
  const entries = await fs.readdir(root, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      if (IGNORED_DIRECTORY_NAMES.has(entry.name.toLowerCase())) continue;
      await walk(fullPath, onFile);
    } else if (entry.isFile()) {
      await onFile(fullPath, await fs.stat(fullPath));
    }
  }
}

function normalizeRelativePath(relativePath) {
  return relativePath.split(path.sep).join('/');
}

function escapeXml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function createTempPath(filePath) {
  const dir = path.dirname(filePath);
  const ext = path.extname(filePath);
  const baseName = path.basename(filePath, ext);
  return path.join(dir, `${baseName}.mediapolotx-tmp${ext}`);
}

function getDefaultBackupDir(folderPath) {
  return path.join(path.dirname(folderPath), `${path.basename(folderPath)}_mediapolotx_backup`);
}

module.exports = {
  scanFolder,
  processFolder,
  detectAiMarkers
};
